#Configuração de rotas
/login-form:  LoginFormController
/login: LoginController
/logout:  LogoutController
/404found:  path404Controller
/main: MainController

/storeUsuario: StoreUsuarioController
/editarUsuario: EditarUsuarioFormController
/deletarUsuario: DeletarUsuarioController
/inativarUsuario: InativarUsuarioController

/formValidaUser: FormValidaUserController
/validaUser: ValidaUserController

/gerenciarAdmin: GerenciarAdminController
/cadastrarAdmin: CadastrarAdminController

/getQrCode: GetQrCodeController
/gerenciarQrCode: GerenciarQrCodeController
/cadastrarQrCode: CadastrarQrCodeController
/storeQrCode: StoreQrCodeController
/editarQrCode: EditarQrCodeFormController
/deletarQrCode: DeletarQrCodeController
/geraQrCode: GeraQrCodeController
